version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-u
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_uni:/var/jenkins_uni

volumes:
  jenkins_uni: