name: CI/CD Pipeline Django

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Compose
      run: |
        docker-compose build

    - name: Run Migrations
      run: |
        docker-compose run web python manage.py migrate --noinput

    - name: Run Tests
      run: |
        docker-compose run web pytest --ds=app.settings --cov=. --cov-report=xml
    
    - name: Generate Coverage Report
      run: |
        docker-compose run web coverage html
