name: Django CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: comida753
          POSTGRES_DB: que_hay_pa_comer
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test PostgreSQL connectivity
        run: |
          sudo apt-get install -y postgresql-client
          pg_isready -h localhost -p 5432 -U postgres
        env:
          PGUSER: postgres
          PGPASSWORD: comida753

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U postgres && break || sleep 5;
          done
        env:
          PGUSER: postgres
          PGPASSWORD: comida753

      - name: Run Tests with Pytest
        run: |
          # pytest --ds=app.settings --cov=. --cov-report=xml
          python manage.py test
